### ISSUE TITLE
Cannot set as "session cookie"

### ISSUE THREAD

**Issue by enmielado** [vvo/iron-session#409]
This [comment](https://github.com/vvo/next-iron-session/issues/85#issuecomment-947594831) suggests the possibility of setting the cookie as a "session cookie" (and the potential shortcomings of doing so), but it seems this is not possible because a value for Max-Age is always set. Is it possible to create the cookie as a "session cookie"?

**Comment by vvo** [comment]
Hey there, I just update the library and you can now pass maxAge: undefined to get session cookies. You first have to upgrade to v6 though, see here: https://github.com/vvo/iron-session/releases/tag/v6.0.0

**Comment by enmielado** [comment]
Much appreciated. Thanks for the fast work.
