### ISSUE TITLE
Accessing the request object

### ISSUE THREAD

**Issue by josiahwiebe** [vvo/iron-session#410]
I'm using next-iron-session on a project that uses dynamic routes, and I'd like to be able to dynamically set the cookie name based on the route being accessed. 

Can I access the request object in the `withIronSession` function? That way I could grab the `req.headers.host` property.

**Comment by vvo** [comment]
Hey @josiahwiebe. I just published a brand new version of iron-session, see here: https://github.com/vvo/iron-session/releases/tag/v6.0.0

About your question, for now it's now feasible but we could easily add it and it would also solve other issues maybe. For example we could allow cookieName to be a method that would be called right before the cookie is serialized/unserialized and you would have to pass your options there.

You would also access the req/res object inside it.

It would look like this:

```js
withIronSessionApiRoute(function (req, res) {

}, {
  password: "...",
  cookieName: function(req, res) {
    return `cookieName${req.somethingComputed}`
  }
})
```

Let me know what you think. I would also appreciate you having a look on how to implement that. You can clone the repository, add a test and see how it goes. Thanks!

**Comment by josiahwiebe** [comment]
Thanks @vvo! I updated right away, was fairly seamless. Thanks for the release!

I'll take a look at creating a PR on that soon. I figured out an alternate solution for now, but still wouldn't mind solving it. I don't have a tonne of TS experience so it will be a good exercise!

**Comment by vvo** [comment]
Hey @josiahwiebe you could start duplicating this test here: https://github.com/vvo/iron-session/blob/bd98c524d9aefaf6d5a87d4836e4adcbcb4c121d/src/index.test.ts#L83-L113

Don't bother too much about TypeScript for now, you can put `// @ts-ignore vvo will fix` in front of any line that fails for you

And:
1. duplicate the test and add change test( to test.only(
1. pass different defaultOptions with a cookieName being a function
1. fiddle around this line: `const seal = cookie.split(";")[0].split("=")[1];` to get the cookieName being sent on the header (right now it strips down everything to get only the cookie value)
1. run `npx jest` to see the test failing

Once you have a failing test you can try implementing it.

Or if you're not a fan of TDD you can try to update the `example/next.js` and pass a cookieName of a function. To develop locally you will have to run `npm link` inside the root of the project and then `npm link iron-session` inside the root of the example/next.js.

This feels very complex I agree I need to add instructions on how to contribute :)

**Comment by ricardotx** [comment]
It's possible to do something like this to be able to dynamically set the cookie max-age? 
Would be handy to set the max-age based of the "remember me" flag from the login form to create a session or a persistent session cookie.

**Comment by vvo** [comment]
@ricardotx Yes we could use the same technique for maxAge computation (allow passing a function for cookieOptions)

**Comment by ricardotx** [comment]
@vvo it would be great! Thank you.

**Comment by searchableguy** [comment]
Any update on the maxCookieAge being able to change dynamically?

**Comment by thomasop** [comment]
hello I don’t understand how to dynamically add maxing. for example the client will check the remember me box and send the value in the body (true, false). I use typescript and it makes me an error when I try to add a function to maxage and even I can not access the body of the request. If anyone has an example code! Thank you

**Comment by vvo** [comment]
iron-session v8 solves this since you have to get the session yourself, 👍
