### ISSUE TITLE
Can't configure secure cookies when webserver deployed behind an SSL facade

### ISSUE THREAD

**Issue by araqnid** [vvo/iron-session#412]
As far as I can tell, iron-session will only use the TLS attribute of the socket to verify that the request is https in order to allow setting the 'secure' attribute of the cookie. We deploy our apps behind a facade that terminates the SSL and passes the request to the nextjs server over plain http -- so I need to override this behaviour (or some ugly workaround).

Would it be reasonable to allow the 'secure' option to have a setting that means "set the secure flag even if the request doesn't look like http, if it breaks you get to keep the pieces"? Or possibly override the predicate for testing whether a request has arrived over HTTPS?

**Comment by vvo** [comment]
Hey there, you're definitely right and a fix was released to solve that in the latest version v6.0.2 can you try it?

Thanks!

**Comment by araqnid** [comment]
Ah, we were some way behind on versions. I've updated now and it works just as needed. Thank you!
