### ISSUE TITLE
Gatsby

### ISSUE THREAD

**Issue by kogan007** [vvo/iron-session#415]
Hi Vincent I just wanted to let you know that the code for the next api route works just as well with the gatsby functions, so you might want to add that as a folder and to the readme. You just need to get rid of nextjs types for it to work.

**Comment by vvo** [comment]
Hey, @kogan007, thanks for the notice, and I hope you like the module!

We could also create a specific import endpoint for Gatsby with the suitable types. What do you think?

If you have an example gatsby project with a function using iron-session, that would be awesome!
