### ISSUE TITLE
ironSession as a Next Middleware

### ISSUE THREAD

**Issue by itsmelion** [vvo/iron-session#416]
### [QUESTION]
Hey. I Just upgraded my app from `next-iron-session` to  `iron-session`.
But one thing i had before and i could not cleanly refactor with was using iron-session as a `next-connect` middleware.

Before i could simply declare this function:
```js
import { ironSession } from 'next-iron-session';
export const withSession = ironSession(sessionConfig);
```
And use middleware (express/connect) like pipes via 'next-connect' no problem like:
```js
route
  .use(cors)
  .use(logger)
  .use(drugs)
  .use(withSession) // <- HERE
  .post(CreateSomethingHandler);
```

I really like this style, so if im missing something on how to use it now let me know.
i tried the export from `import { ironSession } from 'iron-session/express';` but doesn't work, probably cuz im in next, so not really express.

**Comment by vvo** [comment]
Hey @itsmelion could you create a small example so I can try it online?

**Comment by itsmelion** [comment]
Sure!
I did this sandbox with all ways i tried to declare a route with session.
Only one of them is working for me.
https://codesandbox.io/s/busy-sound-s5n05?file=/middlewares/withSession.js

worth noting that on my project, currently iron-session@6.0.2 the export mentioned [here](https://github.com/vvo/iron-session#express-ironsessionironoptions) in the Readme is not present:
![image](https://user-images.githubusercontent.com/12537491/142207210-2a79c31c-7a63-421a-9362-bed1749823d3.png)

**Comment by vvo** [comment]
Hey there @itsmelion the documentation was updated, you should be using:

```ts
import { ironSession } from "iron-session/express";
```

Even in your Next.js code, this should be working, if not let me know what needs to be updated from your point of view.

**Comment by Brawl345** [comment]
I'm also using next-connect and 
```javascript
import { ironSession } from "iron-session/express";
```

worked!

**Comment by deadcoder0904** [comment]
@vvo thank you, this is good but why not export it from `/next` instead?

**Comment by vvo** [comment]
@deadcoder0904 This is really an Express middleware that happens to work in different environments like next-connect. But this is not a Next.js middleware since Next.js has no middleware pattern like Express (req, res, next)

**Comment by deadcoder0904** [comment]
oh cool, that makes sense!
