### ISSUE TITLE
`secure` not set properly for Next.js

### ISSUE THREAD

**Issue by ianjakobs** [vvo/iron-session#425]
I tried using `__Host-Authentication` as the cookie name in production, but it kept failing to set the cookie. When I tried another name it worked, and that's when I saw that the `secure` flag wasn't set, even though I was checking it on a Vercel preview URL (which uses `https`). You can see the same happening for [the demo](https://iron-session-example.vercel.app/) linked in the README.

According to the docs the `secure` flag is supposed to be set based on the protocol being used, but [the code](https://github.com/vvo/iron-session/blob/main/src/index.ts#L135-L140) for this checks for an `encrypted` property on `req.socket` and that doesn't seem to exist.

I found that Vercel has a header called [`x-forwarded-proto`](https://vercel.com/docs/concepts/edge-network/headers#x-forwarded-host) that represents the protocol, but I'm not sure if that'd be a good alternative for this library since not everyone might be using Vercel for hosting.

**Comment by vvo** [comment]
Hey, there I just released a new version to fix this. Sorry about the issue and thanks A LOT for noticing it.
