### ISSUE TITLE
Call to useSWR

### ISSUE THREAD

**Issue by davebm1** [vvo/iron-session#430]
Hi,

Should the call to useSWR in '/examples/next.js/lib/useUser.js' specify a fetcher?

ie.
`import fetchJson from "./fetchJson";`
`const { data: user, mutate: mutateUser } = useSWR("/api/user", fetchJson);`

This is the method given in the [npm package page](https://www.npmjs.com/package/swr) for swr. I found it to be necessary for successful authentication for one of my development applications.

Thanks

Dave

**Comment by vvo** [comment]
Hey @davebm1 we use the SWRConfig here: https://github.com/vvo/iron-session/blob/main/examples/next.js/pages/_app.js

https://swr.vercel.app/docs/global-configuration

That should be enough, let me know.

**Comment by davebm1** [comment]
Thanks Vincent. I understand now.

Regards
Dave
