### ISSUE TITLE
Example improvement

### ISSUE THREAD

**Issue by Izhaki** [vvo/iron-session#437]
Whilst working on an [additional example](https://github.com/Izhaki/iron-session/tree/refactored-example/examples/next.js-embedded-magic-code) ([code at the time of writing](https://github.com/Izhaki/iron-session/tree/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code)), I've spotted a few possible improvements to the examples in this repo.

I know the example is not part of the published library, but I reckon quite a few people will use it for inspiration/bootstrap.

# Context vs Component based fetching of session (critical)

Currently, we have `useUser`, which in turn uses the `useSWR` hook.

The specific issue with this is that `useSWR` revalidates on mount, which means an API call to `/api/user` (which might need to access a DB), and you cannot set `revalidateOnMount` to false because then it won't fetch when you land on the page.

Concretely, after you login and being redirect to the (SG) profile page, the mount on that page calls `/api/user` again, despite the fact that the session was just updated via login. It will fetch the session again whenever you transition between pages.

**Note:** I cannot reproduce this in the deployed version, where the `dedupingInterval` seems to take priority over the any mount, but I defo seen this on local, so still investigating.

This is not how sessions are typically handled in the frontend. Instead, the session is handled at a top-level `SessionProvider` and refreshing it happens on demand (login/logout/polling interval/etc).

So in my refactor there is a  [SessionProvider](https://github.com/Izhaki/iron-session/blob/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code/lib/SessionProvider.tsx) which adds the session (previously user, see next point) to a context. Components use [useSession](https://github.com/Izhaki/iron-session/blob/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code/lib/useSession.ts), which is really just a wrapper around `useContext`.

With this approach, the session is fetched once when `SessionProvider` is mounted, and only refreshed upon login, logout (we can add explicit `refresh()` there, or support for a polling interval).

Another thing worth pointing out is that the login/logout logic moved to the `SessionProvider` so components don't need to bring in the dependencies involved in these (like `fetchJson`). This is also about Separation of Concerns.

# Session rather than User as focus

Having user as the main data passed from the server, and in the client code makes a lot of sense with the current example, because the session only has a user and nothing else.

But, the session may include some additional information, for instance, its expiry date (so users can be notified their session is about to expire).

So on my branch it is session, rather than user that is the focal data. The changes involved are mostly in [this commit](https://github.com/Izhaki/iron-session/commit/0ad2a02a41033d807c96327f0703f7d04bd1f71b).

# Other improvement

## withAccessRestrictions

The client side redirection logic has moved from `useUser` into a dedicated [withAccessRestrictions](https://github.com/Izhaki/iron-session/blob/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code/lib/withAccessRestrictions.tsx), which supports loading, admin role predicates (not just logged-in), and can be used this way:

```ts
export default withAccessRestrictions({
  hasAccess: (user) => Boolean(user?.isLoggedIn),
  unauthorizedRedirect: "/login",
  loading: <div>Loading...</div>,
})(SgProfile);
```

## withSession

Added a [withSession wrappers](https://github.com/Izhaki/iron-session/blob/d2e7a825f1652f694ede440d3c383124018a8794/examples/next.js-embedded-magic-code/lib/withSession.ts) per the [README](https://github.com/vvo/iron-session/blob/dab76011ee9951b358db5e7d80dad45cb5453043/README.md#session-wrappers).

## react-bootstrap & css modules only

- Bootstrap - just to reduce noise (style blocks) and get a slightly better UI. 
- CSS Modules only - rather arbitrary, but some prefer it as it is better performing than CSS-in-JSS.

Currently the re-worked example looks like this:

![iron-session-rework](https://user-images.githubusercontent.com/880132/144633094-f5ffec5e-82bc-48b6-9246-b52012bc8bd4.gif)

Other small changes include a bit more attention to what is imported from where.

**Comment by ludo237** [comment]
I really like the improvements for `useSWR`
