### ISSUE TITLE
Why is `session` only accessible from `req` and not `res`?

### ISSUE THREAD

**Issue by Izhaki** [vvo/iron-session#442]
I guess the original idea was to attach `session` to the `req`,so you can read values from it like so:

```js
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    // ...
  }
```

This makes sense.

But this makes less sense:

```js
  async function loginRoute(req, res) {
    // get user from database then:
    req.session.user = {
      id: 230,
      admin: true,
    };
    await req.session.save();
    res.send({ ok: true });
  },
```

Because this all looks as if you are mutating the request, whereas in practice you really want to mutate the response. Also, internally, `session.save()` adds `set-cookie` to the `res`, not `req`.

Note that we are saving the session on `req`, but then submit `res`. If you really pay attention, it is as if some magic happened.

For correctness sake, I think `session` should be also added to `res`, so the code above changes to:

```js
  async function loginRoute(req, res) {
    // get user from database then:
    res.session.user = {
      id: 230,
      admin: true,
    };
    await res.session.save();
    res.send({ ok: true });
  },
```

**Comment by rametta** [comment]
I agree with this proposal
