### ISSUE TITLE
Question: Auth flow

### ISSUE THREAD

**Issue by agustingabiola** [vvo/iron-session#445]
First of all thanks for this great library, impressive work. Though I'm stuck with the auth flow using next.js + next-connect. Identity provider call me with a POST to my route:

```
handler.post(
  `${AUTH_HANDLER_URL}/callback`,
  withSessionRoute(async (req, res) => {
    console.log('🚀 -----------------------------------------------------------------');
    console.log('🚀 ~ Calling /auth/callback\n', req.body, '\nsession info:', req.session);
    console.log('🚀 -----------------------------------------------------------------');

    res.redirect('/')
  }),
);
```

But I don't get why req.session is not hydrated. I see the session key in the cookies with the information but they don't travel when doing the POST. Maybe it's a noob question and not related to the library so sorry about that.

**Comment by vvo** [comment]
Hey there, maybe double check your secure option to iron-session, it should be false in HTTP and true in https

**Comment by agustingabiola** [comment]
@vvo Thanks a lot for answering. The thing is that I can see the session cookie if it's not a POST (redirection) from the oauth flow. Path, secure, etc look good.
![image](https://user-images.githubusercontent.com/1523829/145825888-0cd102d3-7499-4edf-bc7c-503f46843c63.png)

**Comment by agustingabiola** [comment]
Hi @vvo I've had time to review the oauth flow again and realized what was wrong. Turns out the issue was not in the libraries but myself. When you do a POST to the Nextjs api it's expected to not get any cookies since you are being called from a different "site". In order to fix this you need to set the cookies you want to read at the POST stage with sameSite: "none" (and secure true) instead of the default "lax". Setting the cookies you need this way will ensure you can read them when using the response type "form_post".
