### ISSUE TITLE
ApplySession for Iron-Session

### ISSUE THREAD

**Issue by otitonium** [vvo/iron-session#447]
Hello,

We were using Next-Iron-Session for an application but recently realized that it was deprecated. In our application, we are using applySession() inside getInitialProps() to move and persist data from session to authprovider throughout the application.

How can we replicate applySession() functionality in Iron-session. Seems like both withSessionSsr, withSession does not work in _app file. How can start and get session within _app? Maybe we are using this updated Iron-Session the wrong way.

Thank you in advance.
- Otito

**Comment by Howard86** [comment]
@otitonium 
To use `iron-session` in `getInitialProps`, I learn from source code and use it in the following ways

```ts
MyApp.getInitialProps = async (appContext: AppContext) => {
  const appProps = await App.getInitialProps(appContext)
  
  if (appContext.ctx.req && appContext.ctx.res) {
    const { user } = await getIronSession(
      appContext.ctx.req,
      appContext.ctx.res,
      ironOptions,
    );

    return {
      ...appProps,
      user
    };
  }

  // here as server-side's already given a valid user, client side should handle the case when navigating
  return appProps
};
```

Then we can see `user` as props in the `MyApp` component


Reference: 
- source code: https://github.com/vvo/iron-session/blob/main/next/index.ts#L41
- next.js getInitialProps: https://nextjs.org/docs/api-reference/data-fetching/getInitialProps#context-object

**Comment by sankaracuisine** [comment]
@Howard86 thank you a lot. Your recommendation worked for me. Have a great year

**Comment by otitonium** [comment]
@Howard86 thank you a lot. Your recommendation worked for me. Have a great year
