### ISSUE TITLE
Question - Where is the session actually stored (filesystem) ? Can I change storage

### ISSUE THREAD

**Issue by kristijorgji** [vvo/iron-session#454]
Hi, I am using this together with nextjs.

One example of me setting the session
```
const session = {exampleUserId: 1};
req.session.set('user', session);
await req.session.save();
```

this works fine, but we need for our app to have centralised session storage (redis).
As we have multple express(next) servers responding to the user requests, session must be centralised as well.

How can we tell iron-session to use redis ?

Is that simple example session object stored in a cookie as string (stringified) or what

**Comment by vvo** [comment]
Hey there, the session data is encrypted and stored in cookies. If you want your session data to be in a central store then you'll want to use https://github.com/hoangvvo/next-session
