### ISSUE TITLE
Auto-Logout within a duration

### ISSUE THREAD

**Issue by apidev234** [vvo/iron-session#460]
I store some sensitive data in req.session which can change anytime. So, is there a way that user would get logged out every 6hrs? Is it the ttl? I am not sure :(

**Comment by Mencraft** [comment]
yes it is the ttl you can set it to clear the session after 6 hours

**Comment by vvo** [comment]
Yes it's the ttl indeed.

One thing to keep in mind: the TTL is reset everytime you save the session. So if a user is constantly using your website and you have so session.save calls then it will never expire.

The expire is triggered when someone doesn't use your website for 6 hours.
