### ISSUE TITLE
Flash with node-express implementation

### ISSUE THREAD

**Issue by davebm1** [vvo/iron-session#471]
Vincent,

I know this is old-school, but is there any way I can use express-flash with iron-session? (in a node-express implementation).

Flash depends on express-session, but can it work with iron-session?

Many thanks,

Dave

**Comment by vvo** [comment]
Hey @davebm1 I don't think both would be compatible just like that.
If you think about it, flash messages are just session data that you set once and remove right after reading.

Depending on your type of application you could try to implement it quickly and see how it goes.

The flash implementation is this: https://github.com/jaredhanson/connect-flash/blob/master/lib/flash.js

good luck!

**Comment by davebm1** [comment]
Vincent,

Thanks for the reply.  I guess the question I'm really asking is, "is there a way to store a message in iron-session?"

I'm not suggesting that it be implemented, just wondering if a method currently exists.

I tried running express-session concurrently with iron-session but flash messages were not stored in either.


Thanks

Dave

**Comment by vvo** [comment]
>  "is there a way to store a message in iron-session?"
Yes, you can store anything you want in iron-session, give it a try.

**Comment by vvo** [comment]
@davebm1 You can see the usage right here: https://github.com/vvo/iron-session#usage-nextjs

**Comment by davebm1** [comment]
req.session.message = { info: 'Unauthorised' }
    await req.session.save();
    req.session.message && console.log(req.session.message.info);  // Unauthorised

Pretty simple then!
