### ISSUE TITLE
Magic link with expiry for reuse prevention

### ISSUE THREAD

**Issue by rarkins** [vvo/iron-session#472]
Given the stateless nature of this library, I assume it’s not possible to generate “one time” magic links, but is it possible to have them with an expiry so that the link lasts for e.g. 15 minutes and cannot be used after then?

**Comment by vvo** [comment]
Hey @rarkins, you can definitely set the expiry in the magic link. Just use the `ttl` option: https://github.com/vvo/iron-session/blob/5a3d7fbde6d0b4fe5b30373ae36467634e66d7d7/src/index.ts#L295

This is not documented so if you want to contribute that's a good small thing to add!
