### ISSUE TITLE
Issue on on a mac not seen on my PC build.

### ISSUE THREAD

**Issue by terrysmith** [vvo/iron-session#483]
Hi,
I have the same project building fine on my PC. Setting up and run the same project on a new Mac Pro M1 I'm running into this issue.
Not sure if it's environmental or not.  Any thoughts?

The promise rejected with the reason:
Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session

**Comment by hungntq** [comment]
the same issue with macos mini M1, and I try to lastest version iron-session but not resolved
