### ISSUE TITLE
withIronSessionSSr GetServerSidePropsContext could use a params type

### ISSUE THREAD

**Issue by tettoffensive** [vvo/iron-session#503]
Here you can see that params should extend `ParsedUrlQuery`:
```ts
export type GetServerSidePropsContext<
  Q extends ParsedUrlQuery = ParsedUrlQuery,
  D extends PreviewData = PreviewData
> = {
 ...
  params?: Q
  ...
}
```
However, you can see that there's no generic passed to `context: GetServerSidePropsContext` here:
```ts
declare function withIronSessionSsr<P extends {
    [key: string]: unknown;
} = {
    [key: string]: unknown;
}>(handler: (context: GetServerSidePropsContext) => GetServerSidePropsResult<P> | Promise<GetServerSidePropsResult<P>>, options: IronSessionOptions | GetIronSessionSSROptions): (context: GetServerSidePropsContext) => Promise<GetServerSidePropsResult<P>>;
```
So when I do this, params doesn't 
```ts
export const getServerSideProps: GetServerSideProps = withIronSessionSsr(
  async ({ req, res: _, params, query }) => {
```

**Comment by vvo** [comment]
> So when I do this, params doesn't

I think you forgot to finish this sentence.

Hey @tettoffensive I struggled hard with getting the right types. So if you 100% believe there should be a type change we can always try it and if folks complain then revert it.

BTW can you finish the sentence/precise a bit more what's not working before the solution? Thanks!

**Comment by tettoffensive** [comment]
@vvo I just meant that params as it is now, shows up as `ParsedUrlQuery`. With the following, I believe you could extend ParsedUrlQuery with the `params` type is. This way you can say whether each param is a `string` or a `string[]`. I don't know if there's a better way?
```ts
function withIronSessionSsr<
  P extends {
    [key: string]: unknown;
  } = {
    [key: string]: unknown;
  },
  Q extends ParsedUrlQuery = ParsedUrlQuery,
  D extends PreviewData = PreviewData,
>(
  handler: (
    context: GetServerSidePropsContext<Q, D>,
  ) => GetServerSidePropsResult<P> | Promise<GetServerSidePropsResult<P>>,
  options: IronSessionOptions | GetIronSessionSSROptions,
): (context: GetServerSidePropsContext<Q, D>) => Promise<GetServerSidePropsResult<P>>;
```
