### ISSUE TITLE
Next JS SWR Exemple returns undefined ! 

### ISSUE THREAD

**Issue by younes-alouani** [vvo/iron-session#521]
Hello everyone, 

I want to use iron-session for my project but reading the next js example, I find that it is not functional. 

Especially the profile page (with static generation). Indeed, the user.ts method calls 
`const { data: user, mutate: mutateUser } = useSWR<User>`
This returns undefined for the session / user.

Instead you should use : 
```
const userSwrFetcher = async () => {
    const response = await fetch('/api/auth/swrUser')
    const data = await response.json()
    return data
  }
const { data: user, mutate: mutateUser } = useSWR<User>("swrUSER", userSwrFetcher);
```

So I wonder if this library is maintained (documentation included?)

also, several "issues" are still in "open" state, some of them dating back to 2021.

**Comment by pruhstal** [comment]
Are you wrapping your `_app.tsx/jsx` in the custom SWR config? 

https://github.com/vvo/iron-session/blob/main/examples/next.js-typescript/pages/_app.tsx#L7-L14

**Comment by janek** [comment]
Thank you @younes-alouani, I was struggling with this pretty hard and your solution helped immediately.

When I wrap my `_app.tsx/jsx` in the SWR config my app stops working, with seemingly no output on the frontend or server. I'll post a solution when I find one.

Perhaps this is something that should be documented more. It seems like people who try to use this example in their own project without much experience with the `swr` concept are likely to run into it.

**Comment by p2436b** [comment]
> Thank you @younes-alouani, I was struggling with this pretty hard and your solution helped immediately.
> 
> When I wrap my `_app.tsx/jsx` in the SWR config my app stops working, with seemingly no output on the frontend or server. I'll post if I debug it.

Do not wrap the _app.tsx in the SWR config, just pass fetchJson like below:
```
const { data: user, mutate: mutateUser } = useSWR<User>(
    '/api/user',
    fetchJson
  );
```

**Comment by p2436b** [comment]
> Thank you @younes-alouani, I was struggling with this pretty hard and your solution helped immediately.
> 
> When I wrap my `_app.tsx/jsx` in the SWR config my app stops working, with seemingly no output on the frontend or server. I'll post if I debug it.

Do not wrap the _app.tsx in the SWR config, just pass the fetcher like below:
```
const { data: user, mutate: mutateUser } = useSWR<User>(
    '/api/user',
    fetchJson
  );
```
