### ISSUE TITLE
When return Not Found in getServerSideProps got TypeError: Cannot redefine property: session

### ISSUE THREAD

**Issue by M4h45amu7x** [vvo/iron-session#523]
How can I fix this?

Code:
```javascript
export default withSessionSsr(async (context) => {
	return { notFound: true };
});
```

Error:
![image](https://user-images.githubusercontent.com/89692002/178688849-61f0ac4a-6213-4f46-9d36-a13b7752de1d.png)

**Comment by marceljager** [comment]
Same issue here.

My temporary solution is to skip `withIronSessionSsr` when `req.session` already exists.

So, my `_error.ts` looks like this
```tsx
export const getServerSideProps = async (context) => {
  if (context.req.session) {
    return {
      props: {
        user: context.req.session.user
      },
    };
  }
  
  return withIronSessionSsr(({ req }) => {
    return {
      props: {
        user: req.session.user
      },
    };
  }, options)(context);
}
```

**Comment by isa95Ar** [comment]
Hi, I had to replace withIronSessionSsr, I've added this line to get the instance of the session on the server side:

`const ironSession = await getIronSession(appContext.ctx.req,appContext.ctx.res,sessionOptions)`

**Comment by M4h45amu7x** [comment]
Thank you everyone for your help. I will try to fix
