### ISSUE TITLE
Updating the project for Next 12 SWR Middleware Compatibility

### ISSUE THREAD

**Issue by ChrisCates** [vvo/iron-session#525]
This issue has been in limbo for quite some time now.
It's been "allegedly" solved with a "hack" from: https://github.com/vvo/iron-session/issues/419

But, in reality. This doesn't help at all with current releases of Next given that `buffer`, `stream` and other native Node.js functions aren't available in SWR middleware.
I don't understand why @vvo is claiming that this works with 12.0.4 when it doesn't.

The solution is simple. There are browser native versions of these modules. And, all it takes is to move them over to it.

@vvo, I've seen how your pull request process works. And there's already this PR: https://github.com/vvo/iron-session/pull/510
So I'm not going to bother opening my own.

Do you need money to pick up the PR to completion? This is a pretty valuable project. Just trying to push that PR into completion.

**Comment by helloworld9912** [comment]
Can you accept that PR please?

**Comment by vvo** [comment]
This is now available in 6.2.0, thanks!
