### ISSUE TITLE
Support for Cloudflare Workers and/or Deno

### ISSUE THREAD

**Issue by nathanclevenger** [vvo/iron-session#528]
Since Vercel NextJS Middleware is actually running on Cloudflare Workers, and iron-session runs on that, I'm sure it it could work on Cloudflare Workers and/or Deno, but is there any plans to officially support this?

If we wanted to help contribute to this effort, would that be something that we could propose a pull request for?

**Comment by vvo** [comment]
This is now available in 6.2.0, thanks!

**Comment by nathanclevenger** [comment]
Awesome - thank you!!
