### ISSUE TITLE
Question about environment variable encryption

### ISSUE THREAD

**Issue by Gr3Kidd3r** [vvo/iron-session#531]
What does this line in the main `README` mean and how can I achieve it?
 > :warning: Always store passwords in encrypted environment variables on your platform. Vercel does this automatically.

**Comment by vvo** [comment]
It just means that ideally your password for iron-session is not stored in your GitHub repository as plain text but somehow passed down to your runtime/build. If you create a Vercel environment variable this is what will happen 👍

**Comment by Gr3Kidd3r** [comment]
You mean simply defining my password as an environment variable, but not encrypting it. I'm not using _Vercel_, but a custom local cloud _PaaS_:
1. Should I encrypt that variable?
2. If yes, how is it possible, and will it add any extra security, as the password should live somewhere on the system, and if the attacker can get access to the variable, they can decrypt it too?

**Comment by vvo** [comment]
@Gr3Kidd3r this is up to your decision. You can store the env variables wherever you want. This mention in the README is just to avoid folks storing env variables in plain text somewhere.
