### ISSUE TITLE
Idea: remove withIronSessionApiRoute, withIronSessionSsr and only keep getIronSession

### ISSUE THREAD

**Issue by vvo** [vvo/iron-session#532]
With the introduction of `getIronSession(req, res, options)` in https://github.com/vvo/iron-session/pull/510, knowing all the weird issues people are bumping into when using withIronSessionApiRoute, withIronSessionSsr (especially TS ones). I propose to remove all apis and only keep getIronSession. Then we can let folks write wrappers themselves, and explain them how to do it if that makes sense.

This would drastically reduce our API surface.

Thoughts @brc-dd?

**Comment by brc-dd** [comment]
I can start working on this. I don't think people will have any (much?) issue with this. This should _ideally_ make stuff cleaner.

There is another thing I wanted to ask, can you talk internally with folks at Vercel and see if they can make middleware not complain if the node:crypto module is imported but never used? Maybe, some way to mark dead code in middleware? I'm asking this because many of the issue that we have got recently, there were people just mixing edge and non-edge versions.

**Comment by vvo** [comment]
@brc-dd I will be off for two weeks (moving from our house) but feel free to make progress on this YES!

**Comment by brc-dd** [comment]
We can drop the `/edge` version too. In Next.js 13, middleware uses the browser field instead of module while resolving. [Something like this works:](https://github.com/brc-dd/iron-session/tree/v7)

https://github.com/vvo/iron-session/blob/d55d9eef595dbf2b0198e19f6a01388cf6b3601c/package.json#L23-L30

I'll clean up and submit a PR in some days.

**Comment by brc-dd** [comment]
Worked on the new app directory support. The API looks similar to this now 👀 

```tsx
// app/page.tsx

import { getSessionData } from '@/lib/useSession'
import { cookies } from 'next/headers'

export default async function Home() {
  const data = await getSessionData(cookies())

  return <div>...</div>
}
```

```ts
// api/login/route.ts

import { getSession } from '@/lib/useSession'
import { createResponse } from '@/lib/utils'

export async function GET(req: Request) {
  const [session, res] = await getSession(req)

  // do auth here, for demo:
  session.user = { id: 1, admin: true }

  await session.save()
  return createResponse(res, JSON.stringify({ user: session.user }), {
    headers: { 'Content-Type': 'application/json' }
  })
}
```

**Comment by vvo** [comment]
Thanks @brc-dd, one question I have: why is iron-session responsible for creating a basic `res`?

> const [session, res] = await getSession(req)

**Comment by brc-dd** [comment]
@vvo It isn't actually. I had that in my wrapper, but we can just have:

```ts
const res = new Response()
const session = await getSession(req, res)
```

**Comment by vvo** [comment]
Another question for the app/page.tsx:

> const { user } = await getSessionData(cookies())

How does this work exactly? Since the secret key should be server only. Is this for the cases where you want to decrypt session on the client (browser) directly?

**Comment by vvo** [comment]
> const res = new Response()
> const session = await getSession(req, res)

Let's do this perhaps in the beginning and see if there's an appetite for automatically creating the session?

**Comment by brc-dd** [comment]
> How does this work exactly? Since the secret key should be server only. Is this for the cases where you want to decrypt session on the client (browser) directly?

Yeah, it's not for client components. It's for React Server Components. They have access to secrets.

**Comment by vvo** [comment]
> It's not for client components. It's for React Server Components. They have access to secrets.

Nice, you're more advanced than me in this space then :) I guess there's only session data because RSC can't update the session?

**Comment by brc-dd** [comment]
Yeah, updating cookies/headers isn't supported currently. But IG the team is working on it?

**Comment by brc-dd** [comment]
Another thing I wanted to ask, do we need to support Node.js 14? Next.js has dropped the support and it will be EOL in a month.

**Comment by vvo** [comment]
We can drop Node.js 14 support 👍

**Comment by EfrainCo** [comment]
Hi! @brc-dd. This is just what I needed. I'm trying it but how is your 'createResponse' function from /lib/utils?
I'm using NextResponse and my session is not saving

**Comment by brc-dd** [comment]
@EfrainCo It might not work with the current code (iron-session v6), but it's basically a helper I wrote to copy headers of a response object to a new one (as we can't update body of a response object after constructing it). This is the code if you need:

```ts
export function mergeHeaders(...headersList: (Headers | HeadersInit | undefined)[]): Headers {
  const mergedHeaders = new Headers()
  for (const headers of headersList) {
    const headersObj = headers instanceof Headers ? headers : new Headers(headers)
    for (const [key, value] of headersObj.entries()) {
      mergedHeaders.append(key, value)
    }
  }
  return mergedHeaders
}

export function createResponse(
  originalResponse: Response,
  bodyString: string,
  options?: ResponseInit
): Response {
  const clonedOptions: ResponseInit = {
    status: options?.status ?? originalResponse.status,
    statusText: options?.statusText ?? originalResponse.statusText,
    headers: mergeHeaders(options?.headers, originalResponse.headers)
  }
  const newResponse: Response = new Response(bodyString, clonedOptions)
  return newResponse
}
```

**Comment by EfrainCo** [comment]
I see. After 'await session.save()' I can see that the user info is saved with a 'console.log(session)'. But if after that I call another API only with `const [session] = await getSession(req)
  console.log(session)`
  it comes empty

**Comment by brc-dd** [comment]
Because you need to send the headers set by that save function to the client for the cookie to be set. Those headers will be set in the response object that you pass there.

**Comment by EfrainCo** [comment]
Thanks a lot, it worked! 

I'm now facing an issue where after the login the session is saved but once in the home page the session is destroyed.
Being debugging for a bit and it seems like `await getSession(req)` returns empty.

This is my /api/user:
`export async function GET(req: NextRequest) {
  const [session, res] = await getSession(req)
  session.destroy()
  const userInfo = {
    isLoggedIn: false,
    id: '',
    firstName: '',
    lastName: '',
    displayName: '',
    email: ''
  }
  return createResponse(res, JSON.stringify(userInfo), {
    headers: { 'Content-Type': 'application/json' }
  })
}`

**Comment by EfrainCo** [comment]
Thanks a lot! It worked

**Comment by Nikhilkumar8143** [comment]
@brc-dd 

Is this feature published in newer versions?.The last version on npm shows 6 months ago

**Comment by brc-dd** [comment]
@Nikhilkumar8143 Not yet. We are still working on it. Currently refer the main branch for docs.

**Comment by renchris** [comment]
How do we use getIronSession to first set cookies in the header if getIronSession only returns properly needing cookies already in the header? (Note: using v8 alpha in Next app router and React Server Components)
