### ISSUE TITLE
Error Error [SyntaxError]: Unexpected end of JSON input when using middleware nextjs

### ISSUE THREAD

**Issue by markezure** [vvo/iron-session#534]
Hi, well I'm try to validate my user by middleware from Nextjs but I got the error like, i dont know more what to do... So I would like support to solve it.

Ps.: My application is running in javascript

Thank you
![image](https://user-images.githubusercontent.com/12461098/186856419-7218c858-4ffc-49f0-bbf1-3d2a67ba0e58.png)

**Comment by vvo** [comment]
Can you open on your project, on your machine the file `node_modules/iron-webcrypto/index.js` and replace line 295 with:

```
console.log(decrypted, 'log from iron-webcrypto');
return JSON.parse(decrypted);
```

Then find the `console.log(decrypted,...` result in your terminal and send it here. Thanks.

**Comment by vvo** [comment]
Also please be aware that you can't do this:

```
let user = session?.user;
user = {...}
```

You have to do this:

```
session?.user = {
  isLoggedIn...
}
```

You current code in middleware.ts won't work, you're doing:

```
let user = ...
user = {

}

and then 

if (!user) // this will never be false, because you've done user = {}
```

Use simpler code and try again.

I think the issue is that you're doing session.save() with an empty session.

**Comment by markezure** [comment]
@vvo I see, it was a little test before that I do before to open this issue

**Comment by markezure** [comment]
> Also please be aware that you can't do this:
> 
> ```
> let user = session?.user;
> user = {...}
> ```
> 
> You have to do this:
> 
> ```
> session?.user = {
>   isLoggedIn...
> }
> ```
> 
> You current code in middleware.ts won't work, you're doing:
> 
> ```
> let user = ...
> user = {
> 
> }
> 
> and then 
> 
> if (!user) // this will never be false, because you've done user = {}
> ```
> 
> Use simpler code and try again.
> 
> I think the issue is that you're doing session.save() with an empty session.

@vvo I see, it was a little test before that I do before to open this issue

**Comment by markezure** [comment]
I put the console.log as mentioned but it didn't print to the terminal
![image](https://user-images.githubusercontent.com/12461098/186936168-409aa51e-c3e3-4960-8bde-8d8ba4083764.png)

**Comment by brc-dd** [comment]
Hi, can you copy paste and share the code inside middleware.js here?

**Comment by deamondz** [comment]
Hi! any updates here?

**Comment by brc-dd** [comment]
@vvo So, should I just return an empty object or something like null/undefined? Or just throw a meaningful error that can be catch-ed here:

https://github.com/vvo/iron-session/blob/3ce839c4186d6924880ac5ac9adf822fc7ed8891/src/core.ts#L275-L281

**Comment by vvo** [comment]
session.save() without any changes to it should result in an empty object yup I think so.
