### ISSUE TITLE
getIronSession doesn't work with edge-runtime middleware

### ISSUE THREAD

**Issue by Maders** [vvo/iron-session#537]
When I use `getIronSession` (according to your docs) with the stable version of next.js middleware (12.2), which runs on edge runtime. throws this error:
```
error - (middleware)/node_modules/@peculiar/webcrypto/build/webcrypto.es.js (9:0) @ new SubtleCrypto
error - The edge runtime does not support Node.js 'crypto' module.
```
Is there something I missed?
Your help is greatly appreciated; thanks.

![image](https://user-images.githubusercontent.com/9904514/187091609-36d6c974-22ea-46d7-b92d-b26efb61eb66.png)

Packages:
```
"next": "^12.2.5",
"iron-session": "^6.2.0",
```

**Comment by brc-dd** [comment]
Most likely you've imported non-edge version inside your src/core/server/iron-session file.

**Comment by Maders** [comment]
Thank for you help. Yes, I re-exported the custom versions of `withSession Route/Ssr` in the index file of that directory.
Might it be better to mention this in the readme?

**Comment by zeattacker** [comment]
Hello, i had a same problems with iron-session@6.2.0. How do you resolve this issue ? @Maders

Thanks

**Comment by Maders** [comment]
> Hello, i had a same problems with iron-session@6.2.0. How do you resolve this issue ? @Maders

You must not import withSessionSsr or withSessionRoute or any other thing from 'iron-session' in the middleware file. 
In my screenshot, I re-export a custom version of withSession function in the index file of my `src/core/server/iron-session` so the bundler resolves these functions when importing ironOptions

**Comment by firmanjml** [comment]
I'm having the same problem.
Is there a way to fix this?

![image](https://user-images.githubusercontent.com/37127022/188893283-0bb30e08-4406-4cad-b7c6-f0ac37eef7c4.png)
