### ISSUE TITLE
middleware doc typo?

### ISSUE THREAD

**Issue by wlcharlie** [vvo/iron-session#550]
According to doc [middleware usage](https://github.com/vvo/iron-session#nextjs-middlewares-usage) that destory function is used with await but the following source code and api ref [session.destory](https://github.com/vvo/iron-session#sessiondestroy) seem like it is just regular function, might be typo?

https://github.com/vvo/iron-session/blob/c63b9d21284f8ad75274fc4bcc1ee8158e4dc631/src/core.ts#L208

**Comment by brc-dd** [comment]
Yeah looks like a typo. Feel free to create a PR. BTW `await` on non-async functions works too.

**Comment by wlcharlie** [comment]
@brc-dd thanks for the quick reply! Just a bit confused when expecting the function is async or not and you are right about `await` on non-async function. closing issue 😄
