### ISSUE TITLE
Cookie not removed in production

### ISSUE THREAD

**Issue by nboliver** [vvo/iron-session#551]
Using a Next.js api route, the cookie doesn't get removed in production. The api route is simple: 

```
import { withIronSessionApiRoute } from 'iron-session/next';
import { ironSessionConfig } from '@lib/config';

async function logoutRoute(req, res) {
  req.session.destroy();
  res.json({ isLoggedIn: false });
}

export default withIronSessionApiRoute(logoutRoute, ironSessionConfig);
```

When running in production, `req.session` is an empty object after calling `destroy` but the cookie is never removed.

**Comment by brc-dd** [comment]
This seems weird as we already have a test running against this: https://github.com/vvo/iron-session/blob/27c5dbe09e4e8777c28bde1c574ffc49c9541446/next/index.test.ts#L103-L109

And according to the spec, a zero or negative `Max-Age` should expire the cookie immediately.

**Comment by nboliver** [comment]
Yeah - I logged out `res.getHeader('set-cookie')` and it's showing `Max-Age=0`, so it seems like something else is going on. Does `destroy` need `await` or is it possible there's something happening that stopping the headers from being sent?

**Comment by brc-dd** [comment]
Nah, await isn't required. Can you inspect the response headers in your browser's dev tools (network tab) and see if it is receiving headers properly?

**Comment by nboliver** [comment]
No it doesn't appear to be.
Here it is in develop: 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3094055/196557285-7fd38bf7-a622-43fd-92dc-2094ecc1a8a6.png">
And here it is deployed to Vercel on a preview branch: 
![iron-session-destroy](https://user-images.githubusercontent.com/3094055/196558256-bdef3f7b-a53e-48b3-bc8b-239965d11057.jpg)
Any ideas about what could be causing this discrepancy?

**Comment by nboliver** [comment]
@brc-dd figured it out - changing to a POST request fixes it, probably due to Vercel caching. Staring at those 2 screenshots helped! Thanks for the assistance.
