### ISSUE TITLE
NextJS middleware getIronSession always returns empty object {}

### ISSUE THREAD

**Issue by shinnida220** [vvo/iron-session#553]
Hi,

So I have this block of code in my moddleware.js and I can't seem to get the session data out. I keep getting  {}

`// /middleware.js
import { NextResponse } from 'next/server';
import { getIronSession } from 'iron-session/edge';
import appConfig from './app.config';

export const middleware = async (req) => {
	const res = NextResponse.next();

	// console.log(req.cookies);

	if (req.nextUrl.pathname.startsWith('/ma')) {
		const session = await getIronSession(req, res, appConfig.sessionOptions); 
                // the sessionOptions is something like this.
                
                // sessionOptions: {
                //    cookieName: 'Cookie-Name',
                //    password: '64-char-code',
                    // secure: true should be used in production (HTTPS) but can't be used in development (HTTP)
                //    cookieOptions: {
                 //     secure: process.env.NODE_ENV === "production",
                 //   },
                 // },

		// Session data now returns {} without errors or warnings, correct and incorrect passwords both return {}
		console.log(session); //this always shows blank {}
	}

	return res;
};

export const config = {
	matcher: ['/admin/:path*'],
};
`
package versions
"iron-session": "^6.3.1",
 "next": "^12.2.4",
 
 Please help me out.

**Comment by OscarBC** [comment]
I had an issue with the middleware, my issue was with web pack and some imports. What fixed it for me was to define the sessionOptions object directly in the middleware without importing it from other class. Kind of weird but that helped.

**Comment by michaeldoubek** [comment]
Is this considered solved? I have an exactly same issue. NextJS 13. Might provide more information if needed.

**Comment by madjam002** [comment]
Experiencing this also, I switched to calling `unsealData` manually in my middleware and passing the cookie value in and that seems to work.

**Comment by renchris** [comment]
does anyone have a code example of how to solve it?

**Comment by jcmujica** [comment]
same issue here

**Comment by valentincognito** [comment]
I also experience the same issue, on local everything work as intended but in production I can briefly see my cookie before it gets remove instantly and the middleware returns an empty session object. I have tried not importing the sessions options from another file but it didn't help.  As soon as I use await getIronSession() in my middleware it destroys my session object (in production only)

**Comment by valentincognito** [comment]
I don't know if this can help someone but in my case I solved it by adding a matcher to my middleware to exclude all routes except the client ones.

`// /middleware.ts
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { getIronSession } from 'iron-session/edge'

import { sessionOptions } from './lib/session'

export const middleware = async (req: NextRequest) => {
  const res = NextResponse.next()

  const session = await getIronSession(req, res, sessionOptions)

  if (req.nextUrl.pathname.startsWith('/admin')) {
    if(!session.user?.data?.isAdmin) return NextResponse.redirect(new URL('/', req.url))
  }

  return res
}

export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|favicon.png).*)',
  ]
}`

Doing this stopped clearing the session cookie from the browser!

**Comment by foodornt** [comment]
@valentincognito are you sure? 'cause it's still deleting cookies on my end, even if I ignore /api|/_next calls

**Comment by valentincognito** [comment]
@foodornt Yes I am sure it worked for me but we might have different version of next.js or iron-session
At the time I wrote this I was using Next 13.2.4 and iron-session 6.3.1

**Comment by vvo** [comment]
Hey there, we just released v8, if you still have issues, please create a GitHub repository with a reproduction thanks! iron-session v8 is live now 👍 https://github.com/vvo/iron-session
