### ISSUE TITLE
nextjs server components update

### ISSUE THREAD

**Issue by Hooman-studio** [vvo/iron-session#554]
Nextjs server components has a different api from both serversideProps, middleware and api routes. I made a first working version to get the user, but no version of the save and destroy version yet. I'm just leaving this here in case anyone wants to use it and it might be used in a more complete form as a pull request later.

```typescript
// import crypto from "crypto"; (todo: check if this is the right crypto, edge nodejs etc..)
// import { createUnsealData } from "iron-session";
// import { cookies } from "next/headers";
const getUser = async ({
  password,
  cookieName,
}: {
  password: string;
  cookieName: string;
}) => {
  const nextCookies = cookies();
  const cookie = nextCookies.get(cookieName);

  const unsealData = createUnsealData(crypto);
  const sess =
    cookie === undefined
      ? {}
      : await unsealData(cookie, {
          password: { 1: password },
        });
  return sess as unknown as { user: IronSession["user"] };
};
```

**Comment by kayandra** [comment]
I believe next 13 acts weird when looking at util imports, it keeps marking my `utilities/session.ts` file as a client component. To get around this, i had to pass cookies whenever i want to get sessions and this is my solution for now.

```ts
export async function getSessionFromCookies(nextCookies: any) {
  const ironOptions = ironSessionOptions()
  const cookie = nextCookies.get(ironOptions.cookieName)
  const data = await unsealData(cookie as string, {
    password: ironOptions.password,
  })

  return data as IronSessionData
}
```

**Comment by Smirow** [comment]
The cookie API changed in Next 13.0.1, `cookies().get()` now returns an object with the name and value of the cookie, you must use:  `cookies().get(COOKIE_NAME)?.value`.

@kayandra yes, it's a bit picky, but as soon as you segregate your rsc functions in a separate file that is **never imported** by a client component, **or even `/pages/api`**, it should work.

**Comment by lilingxi01** [comment]
> segregate your rsc functions in a separate file that is never imported by a client component, or even /pages/api, it should work.

The most tricky part is that the server-only function cannot even be used in `/pages/api`.

**Comment by muslax** [comment]
My solution is like [https://github.com/vvo/iron-session/issues/560#issuecomment-1324598048](https://github.com/vvo/iron-session/issues/560#issuecomment-1324598048) which I posted with my other account (@poltang). I think now it is more beatiful with layout feature, since we don't need to pollute every single protected page with `useUser({ redirectTo: '/login' })` &mdash; which now has to be client component. And thankfully I can render all of may pages server-side.

**Comment by muslax** [comment]
@lilingxi01 wdym by this:
> The most tricky part is that the server-only function cannot even be used in /pages/api.

What happens in `/pages/api` always server-only.
