### ISSUE TITLE
res.headers.append is not a function

### ISSUE THREAD

**Issue by vizardkill** [vvo/iron-session#555]
I'm having problems implementing serverless, in my Next JS (12.3.1) project

``` Javascript
ERROR Unhandled Promise Rejection {
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: res.headers.append is not a function",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "res.headers.append is not a function",
        "stack": [
            "TypeError: res.headers.append is not a function",
            "    at addToCookies (/var/task/chunks/804.js:16245:17)",
            "    at Object.destroy (/var/task/chunks/804.js:16235:11)",
            "    at validateToken (/var/task/pages/api/validateToken.js:162:17)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: res.headers.append is not a function",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1131:17)",
        "    at process.emit (node:events:527:28)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
    ]
}
```

**Comment by WinKoKoNaing** [comment]
Me too, When deploy to AWS, the problem occur but in vercel  it is working.

**Comment by ykurniawan** [comment]
Also having this issue on AWS right now.

**Comment by OscarBC** [comment]
Me too. Idk where it's coming from. 

I've read some things:
- that this works in vercel and not, because of some issues with webpack  (haven't tried it)
- that aws amplify does not fully support next 12, and officially does up to next 11.  One of the things it does not support is the middleware function in next 12. (Haven't tried downgrading to next 11)

I've tried deploying it directly with serverless and serverless-components and none worked. All gave the issue that "append is not a function". 

I have a feeling that  the headers object somehow it's transformed into an array or a generic object and not an Http Request Headers object.

Locally it works perfectly but deployed on aws lambdas does not.

**Comment by OscarBC** [comment]
I'll send a PR, I think I found a solution for this issue.

**Comment by vizardkill** [comment]
if indeed it only happens when we make use of AWS serverless services , Are they implemented within version 12 of Next or will it come out within version 13?

**Comment by CervarlCG** [comment]
is there any update with this? the PR that @OscarBC wasn't merge so i'm facing the same error on AWS

**Comment by OscarBC** [comment]
> is there any update with this? the PR that @OscarBC wasn't merge so i'm facing the same error on AWS

You can apply it directly in your project:

1) add https://www.npmjs.com/package/patch-package

2) Apply these changes: https://github.com/vvo/iron-session/pull/558/files 
in your node_modules/iron-session

3) Execute: yarn patch-package iron-session.

Then your project would be patched and you would be able to use it. And that way you won't wait until it's deployed.

**Comment by CervarlCG** [comment]
it worked for me, thanks a lot

**Comment by vizardkill** [comment]
Apparently the error only occurs in version 6.3.1 
![image](https://user-images.githubusercontent.com/37307788/227272050-173d9d96-7d28-4958-b565-601863a71f54.png)


This is because the way in which Cookies are stored has changed.
![image](https://user-images.githubusercontent.com/37307788/227272237-cfc3ad35-ab91-425f-bed2-dbf568a784f3.png)

I have my suspicions but I think that AWS within its Serverless process still does not support the append functionality

**Comment by brc-dd** [comment]
> This is because the way in which Cookies are stored has changed.

Yeah, that was done to support middlewares where you get a standard [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) object (or extended `NextResponse`). Currently we support both browser native APIs (`Response`) and Node.js specific APIs (`ServerResponse`). My guess is on AWS, they are providing a non-standard variation of response.

**Comment by brc-dd** [comment]
fixed in v7 branch
