### ISSUE TITLE
getting error: "The edge runtime does not support Node.js 'crypto' module."

### ISSUE THREAD

**Issue by Jared-Dahlke** [vvo/iron-session#556]
hey guys,
I'm using this library for the first time.

I'm running next13 (i'm not using the `app dir` though, just `pages`.
Iron-Session version: 6.3.1

here's my `middleware.ts`:

```
import { getIronSession } from 'iron-session'
import { sessionOptions } from './lib/session'
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export async function middleware(request: NextRequest) {
	const res = NextResponse.next()
	const session = await getIronSession(request, res, sessionOptions)
	const requestHeaders = new Headers(request.headers)
	requestHeaders.set('Authorization', session.user?.jwt || '')

	const response = NextResponse.next({
		request: {
			headers: requestHeaders
		}
	})

	return response
}

```

and here is the error I am getting:

```
error - (middleware)/node_modules/@peculiar/webcrypto/build/webcrypto.es.js (9:0) @ new SubtleCrypto
error - The edge runtime does not support Node.js 'crypto' module.

```

This will be a deal breaker with me unless I can figure out some other way to append my JWT token to all of my api calls.
I used axios interceptors in my CRA app. I'm really sad because this is the only thing that is keeping me from upgrading from CRA to nextjs

ANY help is appreciated

**Comment by brc-dd** [comment]
You need to use `iron-session/edge` in your middleware.

**Comment by Jared-Dahlke** [comment]
@brc-dd  now the error is gone. And I am able to see the JWT in the middleware, but I am unable to set my headers, I am still getting 401 on all of my api calls. Do you guys have an example of how to set auth headers in the middleware?

**Comment by foodornt** [comment]
@Jared-Dahlke 
Have you gotten to solve it? I'm facing the same issue
It's almost like it's destroying the cookies as soon as it can
