### ISSUE TITLE
Does anyone have an example of how to set auth headers in middleware for NextJs?

### ISSUE THREAD

**Issue by Jared-Dahlke** [vvo/iron-session#557]
I have middleware working, but my auth headers are not setting for some reason. I am using axios for all of my api calls. All of my API calls are returning 401/unauthorized.

here is my middleware.ts:
```

import { getIronSession } from 'iron-session/edge'
//import { sessionOptions } from './lib/session'
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export async function middleware(request: NextRequest) {
	const sessionOptions = {
		password: 'REDACTED',
		cookieName: 'iron-session/examples/next.js',
		cookieOptions: {
			secure: process.env.NODE_ENV === 'production'
		}
	}
	// Clone the request headers and set a new header `x-hello-from-middleware1`
	const res = NextResponse.next()
	const session = await getIronSession(request, res, sessionOptions)
	const requestHeaders = new Headers(request.headers)
	requestHeaders.set('x-hello-from-middleware1', 'hello').  *****I DONT SEE THIS IN THE HEADERS 
	requestHeaders.set('Authorization', session.user?.jwt || '')  *****I DONT SEE THIS IN THE HEADERS 

	const response = NextResponse.next({
		request: {
			// New request headers
			headers: requestHeaders
		}
	})

	response.headers.set('x-hello-from-middleware2', 'hello')
	return response
}

```

I am trying to put auth token on all of my REQUEST headers . Maybe `middleware.ts` is not the place to do this. I am pretty new to Next.  I am trying to port over a CRA app , everything is already written in react-query and axios.  I just hit a simple /authenticate API that returns JWT token.

**Comment by brc-dd** [comment]
>  I DONT SEE THIS IN THE HEADERS 

Where are you actually checking those headers? (What's the thing that will see those headers?)

**Comment by brc-dd** [comment]
If you write something like this:

```ts
// middleware.ts
import { NextResponse, type NextMiddleware } from 'next/server'

export const middleware: NextMiddleware = async (req) => {
  req.headers.set('x-foo', 'foo')
  const res = NextResponse.next({
    request: { headers: req.headers }
  })
  res.headers.set('x-bar', 'bar')
  return res
}

export const config = {
  matcher: '/api/hello'
}
```

Then in `/api/hello`, you'll get `x-foo` as `req.header`. In browser, `x-bar` will show in "Response Headers".

**Comment by Jared-Dahlke** [comment]
Well I have this API file where I keep all API calls for my site. They are all using axios:

![image](https://user-images.githubusercontent.com/32936978/199035671-d33876e2-be8e-48e6-b14d-2002e3705d39.png)



Then on each page I have react-query queries hooked up to them, just basic client side react-query, for example:
![image](https://user-images.githubusercontent.com/32936978/199036162-1933f9a3-b3c7-41ec-91e2-2305216dd123.png)

on the CRA app I am using `axios` interceptors like this to add the auth token to every call:
![image](https://user-images.githubusercontent.com/32936978/199036657-3701d000-4eb7-4b7f-b483-46693b4d438f.png)

now I am trying to accomplish the same thing in NextJs so that all of my api calls have an auth token set in the request headers. I tried to use axios interceptors in Next, but could not get them to work, and can not find any example of this.   So now I am trying to see if I can use middleware.ts file to add the auth token headers, and this is where I am so far...

**Comment by Jared-Dahlke** [comment]
> api/hel

ahhhhh so the api call has to be in the /pages/api directory to access the middleware changes?

What is your recommendation for someone who has hundreds of api calls in one file like this? Do i need to create a new file in /pages/api for every one of my API calls?

**Comment by brc-dd** [comment]
I'm not really sure about this, but I **don't** think these functions can be easily refactored into pages/api/... format. Also, the middleware should run for every route in your project if you haven't specified a custom matcher.

**Comment by brc-dd** [comment]
As far as your original question and this library is concerned, simply this works:

```ts
// middleware.ts
import { NextResponse, type NextMiddleware } from 'next/server'
import { getIronSession } from 'iron-session/edge'

export const middleware: NextMiddleware = async (req) => {
  const res = new NextResponse()
  const session = await getIronSession(req, res, {...})
  req.headers.set('Authorization', session.user?.jwt || '')
  return NextResponse.next({
    request: { headers: req.headers }
  })
}
```

```ts
// pages/api/hello.ts
import { type NextApiHandler } from 'next'

const handler: NextApiHandler = (req, res) => {
  if (verify(req.headers.authorization)) {
    res.status(200).json({ authorized: 'true' })
  } else {
    res.status(401).end()
  }
}

export default handler
```

Regarding your other questions, IG StackOverflow and Next.js official Discord server might be good places to ask.
