### ISSUE TITLE
Type error: Property 'session' does not exist on type 'IronSession'.

### ISSUE THREAD

**Issue by ijaspreetsinghh** [vvo/iron-session#559]
IronSession in middleware Failed to compile for VERCEL.
![image](https://user-images.githubusercontent.com/44422128/200095330-f8dd5bab-6c99-42dd-ba84-34d207a9e01f.png)

./middleware.ts:11:11 
Type error: Property 'session' does not exist on type 'IronSession'. 
 > 9 | export const middleware = async (req: NextRequest) => { 
> 10 | const res = NextResponse.next();
> 11 | const { session } = await getIronSession(req, res, ironSessionOptions); 
> | ^ 
> 12 | 
> 13 | if ( 
> 14 | req.nextUrl.pathname.startsWith("/projects") ||
Error: Command "npm run build" exited with 1

On other places I used `import { getIronSession } from "iron-session`
but as node API is not supported on edge runtime, documentations guides to import `import { getIronSession } from "iron-session/edge";`

code for middleware is:
`import { getIronSession } from "iron-session/edge";`
`import { ironSessionOptions } from "./lib/config";`

`export const middleware = async (req: NextRequest) => {`
`  const res = NextResponse.next();`
`  const { session } = await getIronSession(req, res, ironSessionOptions);`  <<< Error Occurs Here ( session does not exist on 'iron-session/edge' but exists on 'iron-session' )
`return res;`
`}`

**Comment by lsbyerley** [comment]
I am also seeing this for `nonce` and `siwe` in a typescript file. How do you get around this?

`res.send({ address: req.session.siwe?.address || null })`

`Type error: Property 'siwe' does not exist on type 'IronSession'.`

**Comment by jterskine** [comment]
@lsbyerley you will need to add properties needed to the `IronSessionData` interface and update your `tsconfig.json`
See example here https://wagmi.sh/examples/sign-in-with-ethereum#prerequisites

<img width="888" alt="CleanShot 2022-11-14 at 17 35 58@2x" src="https://user-images.githubusercontent.com/2965738/201805040-04dbe451-d30f-4893-8e09-0c7c1509465a.png">

**Comment by lsbyerley** [comment]
@jterskine Thank you for pointing this out! Not sure how I missed that, appreciate the tip!
