### ISSUE TITLE
getIronSession with graphql-yoga context

### ISSUE THREAD

**Issue by abdofola** [vvo/iron-session#567]
I'm creating graphql server with `graphql-yoga` in nextjs application. In my `pages/api/graphql.ts` I have the following code :
``` 
import prisma from "@lib/prisma";
import { schema } from "src/graphql/schema";
import { sessionOptions } from "@lib/session";
import { getIronSession } from "iron-session/edge";

export default createYoga({
  schema,
  // Needed to be defined explicitly because our endpoint lives at a different path other than `/graphql`
  graphqlEndpoint: "/api/graphql",
  context: async ({req, res})=>{
     const session = await getIronSession(req, res, sessionOptions);
     if(!session) return {prisma}
     return {prisma, user:session.user}
   }
});
```

when running the server and head to graphql playground by yoga on `localhost:3000/api/graphql`, I get the following error:
`Server Error
Error: no native implementation of WebCrypto is available in current context`

I can't seem to find anything to help with this. if I commented out the line that make use of `getIronSession` everything seems to work fine.

**Comment by brc-dd** [comment]
You're using the `/edge` version. It needs `globalThis.crypto.subtle` (native webcrypto) to work. That isn't available in your context.

**Comment by abdofola** [comment]
What prevents from implementing `globalThis.crypto.subtle` ?
Any future plan to make this work!

**Comment by brc-dd** [comment]
Use the non-edge version. It should be working 👀 

`import { getIronSession } from "iron-session";`
