### ISSUE TITLE
Next.js 13.2 new route.js support (app directory)

### ISSUE THREAD

**Issue by AlanMorel** [vvo/iron-session#570]
I realize this is bleeding edge as this won't even be released until Next 13.2, but just wanted to get the ball rolling ahead of time.

Currently, I don't see a way you can use `iron-session` with the upcoming [route.js](https://beta.nextjs.org/docs/api-reference/file-conventions/route) architecture.

My current implementation of `iron-session` uses `withIronSessionApiRoute` which requires a `handler: NextApiHandler`. This works for now, however, this is being removed in favor of a more generic `request: Request` when the `pages` directory goes away in favor of the `app` directory.

Thanks!

**Comment by willscott085** [comment]
Would be great if iron-session could expose a hook we can use in server-componets

**Comment by AlanMorel** [comment]
Next.js 13.2 is now out, dropping the link for reference:

https://nextjs.org/blog/next-13-2

Looking forward to hearing what can be done to support this, cheers!
