### ISSUE TITLE
TTL isn't being checked

### ISSUE THREAD

**Issue by aidankinzett** [vvo/iron-session#573]
```ts
import { sealData, unsealData } from "iron-session";

const main = async () => {
  const seal = await sealData(
    {
      test: "test",
    },
    {
      password: "complex_password_at_least_32_characters_long",
      ttl: 5, // 5 seconds
    }
  );

  // set a timeout for 10 seconds
  await new Promise((resolve) => {
    setTimeout(() => {
      resolve(undefined);
    }, 10000);
  });

  try {
    const unsealed = await unsealData(seal, {
      password: "complex_password_at_least_32_characters_long",
      ttl: 5,
    });
    console.log(unsealed); // { test: 'test' }
  } catch (error) {
    console.error(error);
  }
};

main();
```

In the code block above I was expecting `unsealData` to throw an error since it has been more than 5 seconds. What am I doing wrong? The `ttl` value doesn't seem to work?

Edit: The same result occurs when logging the seal out, then copying and pasting it into the unseal function

**Comment by brc-dd** [comment]
Try with a larger timeout (>60s)? `iron-webcrypto` allows a difference of 60s between server and client, that's why it is not appearing to be expired 👀

**Comment by brc-dd** [comment]
https://stackblitz.com/edit/node-stkhwa?file=index.js
