### ISSUE TITLE
session.destroy not working in middleware

### ISSUE THREAD

**Issue by dsbrianwebster** [vvo/iron-session#576]
`session.destroy()` works as expected outside of middleware. But when invoking it from middleware via `iron-session/edge`, it appears to have no effect.

NextJS "13.2.4"
Iron Session: "^6.3.1"

```ts
// middleware.ts

import { NextResponse } from 'next/server';
import { getIronSession } from 'iron-session/edge';

import type { NextRequest } from 'next/server';

import { sessionOptions } from '~/server/session';

export const config = {
  matcher: ['/account/:path*'],
};

export const middleware = async (req: NextRequest) => {
  const res = NextResponse.next();

  const session = await getIronSession(req, res, sessionOptions);

  session.destroy(); // ! This is not destroying the session / removing the cookie
  return NextResponse.redirect(new URL('/', req.url));
};
```

**Comment by brc-dd** [comment]
Why are you destroying the session when there is no user in it?

**Comment by dsbrianwebster** [comment]
@brc-dd sorry, this was intended to be simplified bit of code, not a from an actual application. I didn't catch that mistake with the user logic. I removed that conditional entirely to avoid confusion, while still replicating the bug.

**Comment by brc-dd** [comment]
Can you try awaiting it? `await session.destroy()` ?

**Comment by brc-dd** [comment]
For save/destroy to work you need to return the res object you gave it (or copy the headers from it to final response)

**Comment by dsbrianwebster** [comment]
@brc-dd thank you. Yes I did try `await session.destroy()`, but per https://github.com/vvo/iron-session/issues/571 I'm getting a type error there and event with await it was not working.

@brc-dd per your follow up [comment](https://github.com/vvo/iron-session/issues/576#issuecomment-1470455399)... 🙌... that was it! The copying of the header approach suited our use case best because the we want to conditionally redirect depending on what we get back from `getIronSession`.

```ts
export const middleware = async (req: NextRequest) => {
  const res = NextResponse.next();
  const session = await getIronSession(req, res, sessionOptions);

  //  other stuff...

  session.destroy();
  return NextResponse.redirect(new URL('/', req.url), { headers: res.headers });
};
```
Many many thank you's!
