### ISSUE TITLE
TypeError: req.session.touch is not a function with Next.js 13.1.1

### ISSUE THREAD

**Issue by smurf-ss** [vvo/iron-session#577]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/59644046/225948426-7bc681ce-c6ed-4427-834d-f6d62a748af1.png">

**Comment by brc-dd** [comment]
Can you share relevant code?

**Comment by smurf-ss** [comment]
> Can you share relevant code?

I created `/api/login`  follow example and I need store session SSR only. 

package.json

"next": "13.1.1"
"react": "18.2.0"
"react-dom": "18.2.0"

<img width="638" alt="image" src="https://user-images.githubusercontent.com/59644046/226077517-110ccb9a-b652-4821-9e18-65ebc19fca28.png">

**Comment by dlstjq7685** [comment]
@smurf-ss 
i found next13 api components solutions.
try this code.

```ts
`/api/login.ts`

import { NextApiRequest } from 'next'
import { User, sessionOptions } from '@/utils/session'
import { getIronSession } from 'iron-session';
import { NextResponse } from 'next/server';

export async function GET(req: NextApiRequest) {
    const res = NextResponse.next();

    console.log("connect to login route")

    const session = await getIronSession(req, res, sessionOptions);
    console.log("before ", session, session.user === undefined)
    
    if (session.user === undefined) {
        console.log("set user")
        const user = { isLoggedIn: true, login: "sample user", avatarUrl: "avatar_url" } as User
        session.user = user
        await session.save()
    }
    console.log("after ", session)

    return new Response("Hello, Next.js!")

}

`user.ts`
export type User = {
    isLoggedIn: boolean
    login: string
    avatarUrl: string
  }
  
```

**Comment by vvo** [comment]
Hey there, iron-session v8 is live now 👍 https://github.com/vvo/iron-session and compatible with app router. We even have demos: https://get-iron-session.vercel.app/

Good luck.
