### ISSUE TITLE
Feature request: Support for bearer tokens

### ISSUE THREAD

**Issue by villesau** [vvo/iron-session#579]
Thank you for the smooth session handling library!

I'd love to have bearer token support. The use case I'm having is preview links that has view-only access to some resources. We would use iron-session to seal the required data, generate preview url having that sealed data, pass it from the url using bearer token and grant access that way. This would be totally cookieless, but still utilize iron-sessions sealing capabilities etc.

**Comment by brc-dd** [comment]
Use the exposed sealData and unsealData functions. You'll need to handle adding them to headers yourself.

**Comment by villesau** [comment]
Yeah, handling them manually is ofc possible. But would still be beneficial to have "preferred way" that is directly supported by the library so that people do not need to reinvent the wheel and possible security concerns would have been taken into account out of the box.

**Comment by burakkgunduzz** [comment]
I have a separete backend that provides me bearer token for authorization and I need to append it in every request (I am not using any next.js data fetching methods or api routes just client side requests). Is it possible for me to use iron-session, is it supported this way?

**Comment by vvo** [comment]
Closing because this was answered.

**Comment by villesau** [comment]
@vvo The feature request is still valid tho :) Unless you explicitly decide not to support it?

**Comment by vvo** [comment]
@villesau I welcome your feedback and use case definitely. For your use case I feel the sealData and unsealData methods are perfect though:

1. create a seal with sealData like: `const token = sealData({ previewUrl: 'https://example.com/some/preview' })`
2. link to https://example.com/some/preview?token=token
3. open the URL from 2.
4. forward token to any resource you want to control access
5. in your server code, unseal the token to verify previewUrl === actual URL wherever you want
6. done

There are many ways to do it. I've been using sealData for generating magic loging links in Slack to a website directly and it's very very similar.

Do you have a specific API in mind that would make this easier for you?

**Comment by vvo** [comment]
Hey @villesau thank you again, unfortunately, I am still unclear about your feature requirement (besides the solution of bearer: true). When you have time, happy to review a more detailed real-world use case and explanation of how this would work and why you would need it. 👍
