### ISSUE TITLE
Iron-Session initialized with Next.js middleware not available to nextjs api route if iron-session was initialized during request.

### ISSUE THREAD

**Issue by NickDario** [vvo/iron-session#583]
Hi! thanks for iron-session it's a great library. I am experiencing an unexpected behavior that I haven't been able to understand.

I initialize iron-session in nextjs middleware and use /api/session to return the current session data as json.

This works except for on the very first request I am receiving an empty object instead of my session data. I understand the iron session cookie is not set in the request headers but I don't see why that would cause an issue here. 

repro: https://github.com/NickDario/iron-session-empty-at-first

1. Create next app & install (or just pull the repro) then start the server
```sh
# npx create-next-app
# npm i iron-session
# npm i next-connect

git clone https://github.com/NickDario/iron-session-empty-at-first
cd iron-session-empty-at-first
npm run dev
```

2. iron session file
```js
// file: src/lib/session.js
export const sessionOptions = {
  password: "example-password-1234567890-0987654321",
  cookieName: "example",
  cookieOptions: {
    secure: false,
  },
  ttl: 60 * 60 * 24 * 30
};
```

3. iron-session initializiation in middleware
```js
// file: src/middleware.js
import { sessionOptions } from './lib/session';
import { getIronSession } from 'iron-session/edge';
import { NextResponse } from 'next/server'

export const config = {
    matcher: [
        '/((?!_next/static|favicon.ico|assets).*)'
    ]
}
/**
 * 1. Load session
 * 2. Authenticate session or reroute
 */

export async function middleware(req) {
    const res = NextResponse.next()
    console.log('setting session')
    let session = await getIronSession(req,res,sessionOptions)
    session.testCheckValue = "I'm set"
    await session.save()
    console.log(session)
    return  res
}
```

4. API route to return iron-session data
```js
// file: src/pages/api/session.js
import { withIronSessionApiRoute } from "iron-session/next"
import nextConnect from "next-connect";
import { sessionOptions } from '../../lib/session';

// withIronSession
function GetSession(req, res) {
    console.log("get-session", req.session)
    try {
        return res.json(req.session)
    } catch(e) {
        return res.status(404).json({ok: false})
    }
}

const handler = nextConnect();
handler.get(withIronSessionApiRoute(GetSession, sessionOptions))
export default handler
```

5. Make api request (or visit in incognito chrome window) and response is an empty object
```sh
curl -X GET http://localhost:3000/api/session
{}
```

When the cookie is set in the request, the response is the full object, however I don't see why that would mean the response with the session data is empty.
```
// server logs for first request
setting session
{ testCheckValue: 'I\'m set' }
get-session {}

// server logs for second request (with cookie header set)
setting session
{ testCheckValue: 'I\'m set' }
get-session { testCheckValue: "I'm set" }
```

**Comment by krizzu** [comment]
I bumped into the same issue not so long ago - unfortunately did not manage to find a culprit. I thought there was some kind of a race condition between middleware setting the session object and a request, so at first I added some wait time in the API route, before accessing the session object again. Hacky and does not work all the time, as expected.

I worked around it by adding a retry mechanism in the client code if the session object is undefined. It's a hacky workaround, so I appreciate if anyone could shed some light on the issue here 🙏

**Comment by 4hmaad** [comment]
bump!!

**Comment by 4hmaad** [comment]
Here is my hacky approach to get the token in next13 route handlers:
```
export const readSessionFromCookies = async (): Promise<IronSession> => {
  const { cookieName } = sessionOptions

  // first request do not have the cookie
  // so we need to read it from set-cookie header 
  // which is set by iron-session during the first request
  // check src/middleware.ts for more details
  const sealedSession = cookies().get(cookieName)?.value ?? getCookieFromSetCookieHeader(cookieName)

  if (!sealedSession) {
    throw new Error("No session found.");
  }

  const unsealedSession = await unsealData(sealedSession, {
    password: sessionOptions.password,
  }) as unknown;

  return unsealedSession as IronSession;
}


export const getCookieFromSetCookieHeader = (cookieName: string): string => {
  const setCookieHeader = headers().get("set-cookie");
  // cookieName=cookieValue; Path=/; HttpOnly; Secure; SameSite=Lax
  const cookie = setCookieHeader?.split(";").find((cookie) => cookie.includes(cookieName)) as string;
  return cookie.split("=")[1]
}
```

headers() and cookies() are methods provided by NextJS. I am open to suggestions.

**Comment by vvo** [comment]
Hey there, iron-session v8 is live now 👍 https://github.com/vvo/iron-session and compatible with app router. We even have demos: https://get-iron-session.vercel.app/

Good luck.
