### ISSUE TITLE
Why is 14 days 15 days?

### ISSUE THREAD

**Issue by Izhaki** [vvo/iron-session#584]
From the [code](https://github.com/vvo/iron-session/blob/70d2ff14aacb51e83284d51832fdcda539b4dabc/src/core.ts#L13):
```js
const fourteenDaysInSeconds = 15 * 24 * 3600;
```

Could be a typo, an oversight, me being daft, but could also be for a good reason. So which one is it?

**Comment by brc-dd** [comment]
probably a typo. removed in v7.
