### ISSUE TITLE
Add session data to request in Next JS Middle

### ISSUE THREAD

**Issue by younes-alouani** [vvo/iron-session#589]
**Description:**

I have been using the iron-session library for session management in my Next.js application. I have created a middleware function to check if the user is authenticated or not. Here's the code for the middleware:

```
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { getIronSession } from "iron-session/edge";
import { sessionOptions } from "./utils/auth/config";
import { LOGIN_PAGE } from "./paths";

export const middleware = async (req: NextRequest) => {
  const res = NextResponse.next();
  const session = await getIronSession(req, res, sessionOptions);
  const { user } = session;
  console.log("from middleware ", user ? user.id : "No user found");
  if (user) {
    return res;
  } else {
    return NextResponse.redirect(new URL(LOGIN_PAGE, req.url), {
      status: 307, // Temporary redirect status code
      headers: {
        Location: LOGIN_PAGE, // The URL to redirect to
      },
    });
  }
};

export const config = {
  matcher: ["/api/my/:path*", "/my/:path*"],
};
```

In my application, I would like to update the req object within the middleware to include the decrypted session data. This would allow me to access the session data directly in my API routes without the need for the withSessionRoute() wrapper.

Is there a way to enhance the request context to contain the decrypted session data by modifying the middleware function?

I believe this enhancement would provide more flexibility and simplify the usage of the iron-session library in various scenarios. I would appreciate any guidance or suggestions on achieving this.

Thank you for your attention to this matter.

**Comment by brc-dd** [comment]
Most likely this is not possible considering the request/response contexts that we get in the api routes are not the same as the things returned from/modified in the middleware. (Simply put Next.js' middleware don't behave like that of Express/Koa.)

Still keeping this open if someone can suggest some better way.

**Comment by younes-alouani** [comment]
I found a way right now, I hope this will help someone : 
```
if(user){
    res.cookies.set("user", JSON.stringify(user));
    return res;
  } else {
    return NextResponse.redirect(new URL(LOGIN_PAGE, req.url), {
      status: 307, // Temporary redirect status code
      headers: {
        Location: LOGIN_PAGE, // The URL to redirect to
      },
    });
  }
```

Try to reproduce it and if so can you plese update documentation to include this scenario ? 👍  
I think it's helpful !

**Comment by brc-dd** [comment]
Won't you need to do something like `JSON.parse(req.cookies.user)` to access properties? Also, how does this handle setting something in the session from API routes?

**Comment by younes-alouani** [comment]
You need to parse data, this is not the problem. 
Considering setting something. It's true that it's can't be done without calling the withsession wrapper. But My solution is useful when you need to get session to save record related to this session. 
Setting session is generally done in only two apis login and log out. 
So we can say that this solution is viable with the exception of two routes login and log out.

**Comment by vvo** [comment]
Hey there, iron-session v8 is live now 👍 https://github.com/vvo/iron-session and compatible with app router. We even have demos: https://get-iron-session.vercel.app/

Good luck.
