### ISSUE TITLE
How well does iron session handle authentication? With refresh token ?

### ISSUE THREAD

**Issue by thomasop** [vvo/iron-session#602]
Hello I am new here and I will need some information. Already to be sure, iron is a session management system? In the example of integration with nextjs here, we see that when the user logs in he is just logging in. But then does iron session automatically manage a refresh token? Is the example given to us sufficient in terms of security?

I hash my password with bcrypt so there is no problem with that and I know how to do a post login route for my user (see if the user exists, check his password(bcrypt))

is that I have to manage a refresh token on my side and how to do it with iron session ?

Thank you

**Comment by x0y-gt** [comment]
Any example with this?
