### ISSUE TITLE
NextJS 12 + Amplify = "Error: iron-session: Bad usage. Minimum usage is...."

### ISSUE THREAD

**Issue by Ev-Py-2** [vvo/iron-session#605]
I am toying with moving my web-app from a NextJS + Express build to one where my express server is separate and my NextJS webapp is run via Amplify. My repo has no problem building and deploying, but when navigating to the URL every page is a 500 server side error and the only error I can find in any logs provided is as follows:

Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session

It seems my SSR pages that use iron-session are not being handled correctly and I suspect its an interaction between Amplify controlling the SSR functionality and iron-session being wrapped around Next's getServerSideProps. 

Anyone run into this yet? any work arounds? This flow works great on my EBS deployments but Amplify seems to be a different scenario. Thanks!

**Comment by foodornt** [comment]
have you solved it yet? 'cause I ran into the same error, and it seems to me that there's no hope with it
next-auth uses req only without res to extract session, idk what goes in the internals, but this library is deprecated anyways 😥

**Comment by vvo** [comment]
Hey there, I am sorry this seems to be an AWS amplify issue please open an issue on their repo as you may get more specific help (I have no experience with amplify)
