### ISSUE TITLE
Jest test cases are failing throwing the error "TypeError: Cannot redefine property: session"

### ISSUE THREAD

**Issue by priyabubbles** [vvo/iron-session#610]
Jest test cases which are calling the getServersideProps which is wrapped inside the withSessionSsr are failing due to "TypeError: Cannot redefine property: session"

<img width="543" alt="image" src="https://github.com/vvo/iron-session/assets/25613182/b89dde57-5204-482d-b6f3-c388c259d8e6">

**Comment by vvo** [comment]
Hey there @priyabubbles we just released v8 of iron session, if you're still having an issue please open a new issue with a github repository demonstrating the problem. Thanks!
