### ISSUE TITLE
v8 - Attaching session to request

### ISSUE THREAD

**Issue by rune-hansen** [vvo/iron-session#660]
First of all many thanks for the excellent session handling package.

Now that Iron Session no longer attaches itself to the request, is there any reason for why I should not do it myself as middleware. Any reason you can think of for now or in the future that would make it a bad idea.

Regards
Rune

**Comment by vvo** [comment]
Hey there, it's not a bad idea, it's just preference (and there's no good or bad here: it's really just a preference).
If you want to attach it to req.session then you should do it. We won't be breaking that in the future.

Hope this helps!
