### ISSUE TITLE
Migration away from `withIronSessionApiRoute`

### ISSUE THREAD

**Issue by elie222** [vvo/iron-session#679]
Upgrading from v6 to v8 of this package. What's the easiest way to migrate `withIronSessionApiRoute`?

**Comment by mschilde** [comment]
+1 on this. Is there an upgrade guide?

**Comment by sacru2red** [comment]
in my cases, 
```
export default withIronSessionApiRoute(
  async function handler (
    req: NextApiRequest,
    res: NextApiResponse,
  ) {

 ...
}, IronSessionOptions)
```

```
export default async function handler (
    req: NextApiRequest,
    res: NextApiResponse,
) {
    const session = await getIronSession<ApiResonseData>(req, res, IronSessionOptions)
   ...
}
```

**Comment by mattcasey** [comment]
Here's the OG source code: https://github.com/vvo/iron-session/blob/v6/next/index.ts

**Comment by vvo** [comment]
Yep this is how it was done previously: https://github.com/vvo/iron-session/blob/70d2ff14aacb51e83284d51832fdcda539b4dabc/next/index.ts#L19-L46
