### ISSUE TITLE
why getIronSession not work in middleware like in example (App router + client components, route handlers, and SWR)

### ISSUE THREAD

**Issue by thomasop** [vvo/iron-session#694]
Hello I try to follow exemple here : https://get-iron-session.vercel.app/app-router-client-component-route-handler-swr
 but when I try to protect page with middleware like the example, I got this error : "Invariant: Method expects to have requestAsyncStorage, none available"

Get session in example (in middleware) (the problem is with the cookies() I think)  : 

`
const session = await getIronSession<SessionData>(
    cookies(),
    sessionOptions[request.nextUrl.pathname]
  );
`

And when I use this, the middleware work and page is protected  : 
```
      const session = await getIronSession<SessionData>(request, res, {
           cookieName: "iron-examples-app-router-client-component-route-handler-swr",
          password: "complex_password_at_least_32_characters_long",
          cookieOptions: {
               secure: process.env.NODE_ENV === "production",
          },
      });
```

Of course both sessions must be equal (password and cookieName)
Then I can use this as in the second example or I must keep the cookie()

Thank for your help

iron-session: ^8.0.1
next: 13.4.8

**Comment by simpleneeraj** [comment]
Hello, I've successfully implemented and tested the provided code on both development and production environments for my website. This information might be beneficial for you.

Full code 
```ts
import { secrets } from '@/config';
import { NextConfig } from 'next';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import ironCookie from './server/session';
import { getIronSession } from 'iron-session';

const password = String(process.env.NEXT_IRON_SESSION_PASSWORD);

const auth = ['/account/sign-in', '/account/sign-up', '/account/forgot-password', '/account/change-password'];

export async function middleware(request: NextRequest) {
  /**
   * Default User Middleware
   */
  const session = await getIronSession<any>(request.cookies as any, {
    password,
    cookieName: secrets.USER_SESSION,
  });

  const userId = session?.id;
  if (auth.includes(request.nextUrl.pathname)) {
    if (userId) {
      return NextResponse.redirect(new URL('/account/dashboard', request.url), 308);
    }
  } else {
    if (!userId) {
      return NextResponse.redirect(new URL('/account/sign-in', request.url), 308);
    }
  }
}

// See "Matching Paths" below to learn more
export const config: NextConfig = {
  matcher: [
    '/account/:path*', // matches /auth and /account/anything-else
  ],
};

```

**Comment by vvo** [comment]
Hey there, if you still manage to have this issue, please create a very simple GitHub repository where I can experience the issue, the repository needs to be extremely simple for me to help you out (= not a lot of code). As of today middlewares are working as seen in the live example, if they are not for you try to reproduce the issue in a GH repository and I will have a look
