### ISSUE TITLE
Unable to create a session cookie

### ISSUE THREAD

**Issue by Arjan-Zuidema** [vvo/iron-session#712]
How do I make the cookie expire at the end of the session?

I tried multiple combinations of `-1`, `0`, `undefined`, `null` with `ttl` and `expires` but nothing seems to work. The inspector always shows an expire date while it should say `Session` in the expires column.

**Comment by Arjan-Zuidema** [comment]
@vvo @brc-dd anyone? Cannot seem to find any docs about this.

**Comment by brc-dd** [comment]
try with -60 maybe

**Comment by brc-dd** [comment]
Try cookieOptions: { maxAge: undefined }

**Comment by Arjan-Zuidema** [comment]
Looks like that did the trick, thanks 👌🏼
