### ISSUE TITLE
TypeError: can't access property "importKey", _crypto.subtle is undefined

### ISSUE THREAD

**Issue by asharifauzan** [vvo/iron-session#762]
Hello, I just created custom hooks called `useSession()` that will decode current session through `unsealData()` method called in nextjs client component but found the error `TypeError: can't access property "importKey", _crypto.subtle is undefined`.

I also created `getSession()` which has same ability as `useSession()`, but it called in server component and it run perfectly without any error.

![image](https://github.com/vvo/iron-session/assets/52328248/5ab08dd9-4585-4047-97d1-3bf8e024876e)

Libs:
- next@13.4.7
- iron-session@8.0.1

**Comment by asharifauzan** [comment]
> Hello, I just created custom hooks called `useSession()` that will decode current session through `unsealData()` method called in nextjs client component but found the error `TypeError: can't access property "importKey", _crypto.subtle is undefined`.
> 
> I also created `getSession()` which has same ability as `useSession()`, but it called in server component and it run perfectly without any error.
> 
> ![image](https://private-user-images.githubusercontent.com/52328248/338505763-5ab08dd9-4585-4047-97d1-3bf8e024876e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzY5ODcsIm5iZiI6MTcxODE3NjY4NywicGF0aCI6Ii81MjMyODI0OC8zMzg1MDU3NjMtNWFiMDhkZDktNDU4NS00MDQ3LTk3ZDEtM2JmOGUwMjQ4NzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDAxZmU0MmFiZjgzZmJkZjIxOGZjNDgxNGVlMzg3MTAzOWM3MmI2MjhiMjQ1ZTEzZDgyMDkyZGJlMzRkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mTV9TTjhqNJZ0Xu3NsaiI1k4xqpF1BekOMK2YpKjlVc)
> 
> Libs:
> 
>     * next@13.4.7
> 
>     * iron-session@8.0.1

update, the problem is occurs when I open nextjs in `http://HOST` and doesn't occurs when I open `http://localhost`

**Comment by vvo** [comment]
Hey there, if that's what you're trying to do, I do not think you can call unsealData in client components, as unsealing HAS to be done on the server since it require the session private key.

If you're still having issues/misunderstandings comment back, thanks!

**Comment by asharifauzan** [comment]
> Hey there, if that's what you're trying to do, I do not think you can call unsealData in client components, as unsealing HAS to be done on the server since it require the session private key.
> 
> If you're still having issues/misunderstandings comment back, thanks!

thank you, currently we're moving `unsealData` into server component
