### ISSUE TITLE
upgrade the cookie dependency 

### ISSUE THREAD

**Issue by mrananderson** [vvo/iron-session#861]
# npm audit report

cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
No fix available
node_modules/cookie
  iron-session  *
  Depends on vulnerable versions of cookie
  node_modules/iron-session

**Comment by dkindt** [comment]
Can we get an updated ETA on when to expect the cookie dep to be updated? @vvo
